function lambda = lambdaSyphilis(beta,sigma,tau,theta,gamma10,gamma30,nu,mu,rho)
%UNTITLED3 Summary of this function goes here
%   Detailed explanation goes here
    amodif = gamma10*mu^2 + gamma10*rho^2 + 3*mu*rho^2 + 3*mu^2*rho + mu^2*sigma + mu^2*tau + mu^2*theta + rho^2*sigma + rho^2*tau + rho^2*theta + mu^3 + rho^3 - beta*mu*sigma + 2*gamma10*mu*rho - beta*rho*sigma + gamma10*mu*sigma + gamma10*mu*theta - beta*sigma*tau - beta*sigma*theta + gamma10*rho*sigma + gamma10*rho*theta + gamma10*sigma*theta + 2*mu*rho*sigma + 2*mu*rho*tau + 2*mu*rho*theta + mu*sigma*tau + mu*sigma*theta + mu*tau*theta + rho*sigma*tau + rho*sigma*theta + rho*tau*theta + sigma*tau*theta;
    lambda = -((gamma30 + mu + nu + rho)*(amodif))/(gamma10*mu^2 + gamma30*mu^2 +...
        gamma10*rho^2 + gamma30*rho^2 + mu^2*nu + 3*mu*rho^2 + 3*mu^2*rho + nu*rho^2 +...
        mu^2*sigma + mu^2*tau + mu^2*theta + rho^2*sigma + rho^2*tau + rho^2*theta + mu^3 +...
        rho^3 + gamma10*gamma30*mu + gamma10*gamma30*rho + gamma10*gamma30*theta +...
        gamma10*mu*nu + 2*gamma10*mu*rho + 2*gamma30*mu*rho + gamma10*nu*rho +...
        gamma30*mu*sigma + gamma30*mu*tau + gamma10*mu*theta + gamma30*mu*theta +...
        gamma10*nu*theta + gamma30*rho*sigma + gamma30*rho*tau + gamma10*rho*theta +...
        gamma30*rho*theta + 2*mu*nu*rho + gamma30*sigma*tau + gamma30*sigma*theta +...
        mu*nu*sigma + gamma30*tau*theta + mu*nu*tau + mu*nu*theta + 2*mu*rho*sigma +...
        2*mu*rho*tau + 2*mu*rho*theta + nu*rho*sigma + nu*rho*tau + mu*sigma*tau +...
        nu*rho*theta + mu*sigma*theta + mu*tau*theta + nu*sigma*tau + nu*sigma*theta +...
        nu*tau*theta + rho*sigma*tau + rho*sigma*theta + rho*tau*theta + sigma*tau*theta);
end

