function [dY] = ODE_SEIISSICR_v4(t,Y,beta1,nu1,eps1,sigma1,gamma1,...
                                 betaIHIV,betaCHIV,gammaHIV,sigmaHIV,thetaHIV,mu,b,rho)
[~,Lambda1,~] = Rp_SEIIS_v4(beta1,nu1,eps1,sigma1,gamma1,mu,b,rho);
[~,lambdaHIV,~] = Rp_SICR_v4(betaIHIV,betaCHIV,thetaHIV,sigmaHIV,gammaHIV,mu,b,rho);

dY = [b + Y(5)*rho - Y(1)*(Lambda1 + lambdaHIV + mu) + Y(13)*(gamma1 + nu1) + Y(9)*(nu1 + rho);... %S
 Y(1)*lambdaHIV - Y(2)*(Lambda1 + gammaHIV + mu + rho + sigmaHIV) + Y(10)*nu1 + Y(14)*(gamma1 + nu1);... %IHIV, SSTI
 Y(11)*nu1 + Y(2)*sigmaHIV - Y(3)*(Lambda1 + mu + rho + thetaHIV) + Y(15)*(gamma1 + nu1);...
 Y(6)*rho + Y(7)*rho + Y(8)*rho + Y(10)*rho + Y(11)*rho - Y(4)*(Lambda1 + mu) + Y(16)*(gamma1 + nu1) + Y(2)*(gammaHIV + rho) + Y(12)*(nu1 + rho) + Y(3)*(rho + thetaHIV);...
 Lambda1*Y(1) - Y(5)*(lambdaHIV + mu + rho + sigma1);...
 Lambda1*Y(2) + Y(5)*lambdaHIV - Y(6)*(gammaHIV + mu + rho + sigma1 + sigmaHIV);...
 Lambda1*Y(3) + Y(6)*sigmaHIV - Y(7)*(mu + rho + sigma1 + thetaHIV);...
 Lambda1*Y(4) + Y(6)*gammaHIV + Y(7)*thetaHIV - Y(8)*(mu + rho + sigma1);...
 - Y(9)*(lambdaHIV + mu + nu1 + rho) - Y(5)*sigma1*(eps1 - 1);...
 Y(9)*lambdaHIV - Y(10)*(gammaHIV + mu + nu1 + rho + sigmaHIV) - Y(6)*sigma1*(eps1 - 1);...
 Y(10)*sigmaHIV - Y(11)*(mu + nu1 + rho + thetaHIV) - Y(7)*sigma1*(eps1 - 1);...
 Y(10)*gammaHIV + Y(11)*thetaHIV - Y(12)*(mu + nu1 + rho) - Y(8)*sigma1*(eps1 - 1);...
 Y(5)*eps1*sigma1 - Y(13)*(gamma1 + lambdaHIV + mu + nu1);...
 Y(13)*lambdaHIV - Y(14)*(gamma1 + gammaHIV + mu + nu1 + sigmaHIV) + Y(6)*eps1*sigma1;...
 Y(14)*sigmaHIV - Y(15)*(gamma1 + mu + nu1 + thetaHIV) + Y(7)*eps1*sigma1;...
 Y(14)*gammaHIV + Y(15)*thetaHIV - Y(16)*(gamma1 + mu + nu1) + Y(8)*eps1*sigma1];

end