function [dY] = ODE_SICRSEIIIS_v4(t,Y,betaIHIV,betaCHIV,gammaHIV,sigmaHIV,thetaHIV,...
                                 betaSyph,sigmaSyph,tauSyph,nuSyph,gamma1Syph,thetaSyph,gamma3Syph,mu,b,rho)
    %copypaste of ODE_SICRSEIIIS_2 (STIs not implied)    
    %attention entre les noms gamma et theta
    % [ X1, 1, 1]
    % [ X2, 2, 1]
    % [ X3, 3, 1]
    % [ X4, 4, 1]
    % [ X5, 1, 2]
    % [ X6, 2, 2]
    % [ X7, 3, 2]
    % [ X8, 4, 2]
    % [ X9, 1, 3]
    % [X10, 2, 3]
    % [X11, 3, 3]
    % [X12, 4, 3]
    % [X13, 1, 4]
    % [X14, 2, 4]
    % [X15, 3, 4]
    % [X16, 4, 4]
    % [X17, 1, 5]
    % [X18, 2, 5]
    % [X19, 3, 5]
    % [X20, 4, 5] 
    [~,lambdaHIV, ~] = Rp_SICR_v4(betaIHIV,betaCHIV,thetaHIV,sigmaHIV,gammaHIV,mu,b,rho);
    [~,lambdaSyph,~] = Rp_SEIIIS_v4(betaSyph,sigmaSyph,tauSyph,nuSyph,gamma1Syph,thetaSyph,gamma3Syph,mu,b,rho);

    dY = [b + Y(5)*rho + Y(13)*rho - Y(1)*(lambdaHIV + lambdaSyph + mu) + Y(17)*(gamma3Syph + nuSyph + rho) + Y(9)*(gamma1Syph + rho);...
         Y(10)*gamma1Syph + Y(1)*lambdaHIV - Y(2)*(gammaHIV + lambdaSyph + mu + rho + sigmaHIV) + Y(18)*(gamma3Syph + nuSyph);...
         Y(11)*gamma1Syph + Y(2)*sigmaHIV - Y(3)*(lambdaSyph + mu + rho + thetaHIV) + Y(19)*(gamma3Syph + nuSyph);...
         Y(6)*rho + Y(7)*rho + Y(8)*rho + Y(10)*rho + Y(11)*rho + Y(14)*rho + Y(15)*rho + Y(16)*rho + Y(18)*rho + Y(19)*rho + Y(20)*(gamma3Syph + nuSyph + rho) + Y(2)*(gammaHIV + rho) + Y(12)*(gamma1Syph + rho) - Y(4)*(lambdaSyph + mu) + Y(3)*(rho + thetaHIV);...
         Y(1)*lambdaSyph - Y(5)*(lambdaHIV + mu + rho + sigmaSyph);...
         Y(5)*lambdaHIV + Y(2)*lambdaSyph - Y(6)*(gammaHIV + mu + rho + sigmaHIV + sigmaSyph);...
         Y(3)*lambdaSyph + Y(6)*sigmaHIV - Y(7)*(mu + rho + sigmaSyph + thetaHIV);...
         Y(6)*gammaHIV + Y(4)*lambdaSyph + Y(7)*thetaHIV - Y(8)*(mu + rho + sigmaSyph);...
         Y(5)*sigmaSyph - Y(9)*(gamma1Syph + lambdaHIV + mu + rho + tauSyph);...
         Y(9)*lambdaHIV + Y(6)*sigmaSyph - Y(10)*(gammaHIV + gamma1Syph + mu + rho + sigmaHIV + tauSyph);...
         Y(10)*sigmaHIV + Y(7)*sigmaSyph - Y(11)*(gamma1Syph + mu + rho + tauSyph + thetaHIV);...
         Y(10)*gammaHIV + Y(8)*sigmaSyph + Y(11)*thetaHIV - Y(12)*(gamma1Syph + mu + rho + tauSyph);...
         Y(9)*tauSyph - Y(13)*(lambdaHIV + mu + rho + thetaSyph);...
         Y(13)*lambdaHIV + Y(10)*tauSyph - Y(14)*(gammaHIV + mu + rho + sigmaHIV + thetaSyph);...
         Y(14)*sigmaHIV + Y(11)*tauSyph - Y(15)*(mu + rho + thetaHIV + thetaSyph);...
         Y(14)*gammaHIV + Y(12)*tauSyph + Y(15)*thetaHIV - Y(16)*(mu + rho + thetaSyph);...
         Y(13)*thetaSyph - Y(17)*(gamma3Syph + lambdaHIV + mu + nuSyph + rho);...
         Y(17)*lambdaHIV + Y(14)*thetaSyph - Y(18)*(gammaHIV + gamma3Syph + mu + nuSyph + rho + sigmaHIV);...
         Y(18)*sigmaHIV + Y(15)*thetaSyph - Y(19)*(gamma3Syph + mu + nuSyph + rho + thetaHIV);...
         Y(18)*gammaHIV + Y(19)*thetaHIV + Y(16)*thetaSyph - Y(20)*(gamma3Syph + mu + nuSyph + rho)];
end