function [dY]= ODE_SICTPSEIIIS(t,Y,betaIh,betaCh,sigmah,gammah,zetah,etah,ph,...
    betas,sigmas,gamma3s,taus,thetas,...
    tabComp,mu,b,rho)
    %forget to include mandatory routine testing rate of stis under prep

    %by default gamma1S is 0 and does not appear here
    %[~,Lambda1,   ~] = Rp_SEIIS_v4(beta1,nu1,eps1,sigma1,gamma1,mu,b,rho);
    %[~,lambdaSyph,~] = Rp_SEIIIS_v4(betaSyph,sigmaSyph,tauSyph,nuSyph,gamma1Syph,thetaSyph,gamma3Syph,mu,b,rho);
    
    %N = sum(Y);
    N = b/mu; %endemic N
    dY = zeros(length(Y),1);
    
    Lambdah = betaIh*sum(Y([2     5     9    12    16    19    23    26    30    33]))./N +...
        betaCh*sum(Y([3     6    10    13    17    20    24    27    31    34]))./N;
    Lambdas = betas*sum(Y([15    16    17    18    19    20    21    22    23    24    25    26    27    28    29    30    31    32    33    34    35]))./N;

    dY(1) = Y(8)*rho - Y(1)*(Lambdah + Lambdas + mu) + Y(15)*rho + Y(22)*rho - b*(ph - 1) + Y(29)*(gamma3s + rho);...
    dY(2) = Lambdah*Y(1) + Y(30)*gamma3s - Y(2)*(Lambdas + mu + rho + sigmah);...
    dY(3) = Y(31)*gamma3s + Y(2)*sigmah - Y(3)*(Lambdas + gammah + mu + rho);...
    dY(4) = Y(11)*rho + Y(18)*rho + Y(25)*rho + b*ph - Y(4)*(Lambdas + mu - Lambdah*(zetah - 1)) + Y(32)*(gamma3s + rho);...
    dY(5) = Y(33)*gamma3s - Y(5)*(Lambdas + etah + mu + rho + sigmah) - Lambdah*Y(4)*(zetah - 1);...
    dY(6) = Y(34)*gamma3s - Y(6)*(Lambdas + etah + gammah + mu + rho) + Y(5)*sigmah;...
    dY(7) = Y(2)*rho + Y(9)*rho + Y(10)*rho + Y(12)*rho + Y(13)*rho + Y(14)*rho + Y(16)*rho + Y(17)*rho + Y(19)*rho + Y(20)*rho + Y(21)*rho + Y(23)*rho + Y(24)*rho + Y(26)*rho + Y(27)*rho + Y(28)*rho + Y(30)*rho + Y(31)*rho + Y(33)*rho + Y(34)*rho + Y(6)*(etah + gammah + rho) - Y(7)*(Lambdas + mu) + Y(5)*(etah + rho) + Y(3)*(gammah + rho) + Y(35)*(gamma3s + rho);...
    dY(8) = Lambdas*Y(1) - Y(8)*(Lambdah + mu + rho + sigmas);...
    dY(9) = Lambdah*Y(8) + Lambdas*Y(2) - Y(9)*(mu + rho + sigmah + sigmas);...
    dY(10) = Lambdas*Y(3) + Y(9)*sigmah - Y(10)*(gammah + mu + rho + sigmas);...
    dY(11) = Lambdas*Y(4) - Y(11)*(mu + rho + sigmas - Lambdah*(zetah - 1));...
    dY(12) = Lambdas*Y(5) - Y(12)*(etah + mu + rho + sigmah + sigmas) - Lambdah*Y(11)*(zetah - 1);...
    dY(13) = Lambdas*Y(6) + Y(12)*sigmah - Y(13)*(etah + gammah + mu + rho + sigmas);...
    dY(14) = Lambdas*Y(7) + Y(12)*etah + Y(10)*gammah - Y(14)*(mu + rho + sigmas) + Y(13)*(etah + gammah);...
    dY(15) = Y(8)*sigmas - Y(15)*(Lambdah + mu + rho + taus);...
    dY(16) = Lambdah*Y(15) + Y(9)*sigmas - Y(16)*(mu + rho + sigmah + taus);...
    dY(17) = Y(16)*sigmah + Y(10)*sigmas - Y(17)*(gammah + mu + rho + taus);...
    dY(18) = Y(11)*sigmas - Y(18)*(mu + rho + taus - Lambdah*(zetah - 1));...
    dY(19) = Y(12)*sigmas - Y(19)*(etah + mu + rho + sigmah + taus) - Lambdah*Y(18)*(zetah - 1);...
    dY(20) = Y(19)*sigmah + Y(13)*sigmas - Y(20)*(etah + gammah + mu + rho + taus);...
    dY(21) = Y(19)*etah + Y(17)*gammah + Y(14)*sigmas - Y(21)*(mu + rho + taus) + Y(20)*(etah + gammah);...
    dY(22) = Y(15)*taus - Y(22)*(Lambdah + mu + rho + thetas);...
    dY(23) = Lambdah*Y(22) + Y(16)*taus - Y(23)*(mu + rho + sigmah + thetas);...
    dY(24) = Y(23)*sigmah + Y(17)*taus - Y(24)*(gammah + mu + rho + thetas);...
    dY(25) = Y(18)*taus - Y(25)*(mu + rho + thetas - Lambdah*(zetah - 1));...
    dY(26) = Y(19)*taus - Y(26)*(etah + mu + rho + sigmah + thetas) - Lambdah*Y(25)*(zetah - 1);...
    dY(27) = Y(26)*sigmah + Y(20)*taus - Y(27)*(etah + gammah + mu + rho + thetas);...
    dY(28) = Y(26)*etah + Y(24)*gammah + Y(21)*taus - Y(28)*(mu + rho + thetas) + Y(27)*(etah + gammah);...
    dY(29) = Y(22)*thetas - Y(29)*(Lambdah + gamma3s + mu + rho);...
    dY(30) = Lambdah*Y(29) + Y(23)*thetas - Y(30)*(gamma3s + mu + rho + sigmah);...
    dY(31) = Y(30)*sigmah + Y(24)*thetas - Y(31)*(gammah + gamma3s + mu + rho);...
    dY(32) = Y(25)*thetas - Y(32)*(gamma3s + mu + rho - Lambdah*(zetah - 1));...
    dY(33) = Y(26)*thetas - Y(33)*(etah + gamma3s + mu + rho + sigmah) - Lambdah*Y(32)*(zetah - 1);...
    dY(34) = Y(33)*sigmah - Y(34)*(etah + gammah + gamma3s + mu + rho) + Y(27)*thetas;...
    dY(35) = Y(33)*etah + Y(31)*gammah + Y(28)*thetas - Y(35)*(gamma3s + mu + rho) + Y(34)*(etah + gammah);

    %     HIV1    syph1    no        X    
    %     ____    _____    __    _________
    % 
    %     "S"     "S"       1    [1×1 sym]
    %     "I"     "S"       2    [1×1 sym]
    %     "C"     "S"       3    [1×1 sym]
    %     "P"     "S"       4    [1×1 sym]
    %     "Ip"    "S"       5    [1×1 sym]
    %     "Cp"    "S"       6    [1×1 sym]
    %     "T"     "S"       7    [1×1 sym]
    %     "S"     "E"       8    [1×1 sym]
    %     "I"     "E"       9    [1×1 sym]
    %     "C"     "E"      10    [1×1 sym]
    %     "P"     "E"      11    [1×1 sym]
    %     "Ip"    "E"      12    [1×1 sym]
    %     "Cp"    "E"      13    [1×1 sym]
    %     "T"     "E"      14    [1×1 sym]
    %     "S"     "I1"     15    [1×1 sym]
    %     "I"     "I1"     16    [1×1 sym]
    %     "C"     "I1"     17    [1×1 sym]
    %     "P"     "I1"     18    [1×1 sym]
    %     "Ip"    "I1"     19    [1×1 sym]
    %     "Cp"    "I1"     20    [1×1 sym]
    %     "T"     "I1"     21    [1×1 sym]
    %     "S"     "I2"     22    [1×1 sym]
    %     "I"     "I2"     23    [1×1 sym]
    %     "C"     "I2"     24    [1×1 sym]
    %     "P"     "I2"     25    [1×1 sym]
    %     "Ip"    "I2"     26    [1×1 sym]
    %     "Cp"    "I2"     27    [1×1 sym]
    %     "T"     "I2"     28    [1×1 sym]
    %     "S"     "I3"     29    [1×1 sym]
    %     "I"     "I3"     30    [1×1 sym]
    %     "C"     "I3"     31    [1×1 sym]
    %     "P"     "I3"     32    [1×1 sym]
    %     "Ip"    "I3"     33    [1×1 sym]
    %     "Cp"    "I3"     34    [1×1 sym]
    %     "T"     "I3"     35    [1×1 sym]
end

