function [M] = ODESEIIIS(S,E,I1,I2,I3,lambda,sigma,tau,theta,gamma10,gamma30,nu,rho,mu)
%ODE to write
%rho=0 dans M
    %S,E,I1,I2,I3
    M = [-lambda-mu, rho, gamma10+rho, rho,(nu+gamma30+rho);...
        lambda, -(sigma+rho+mu), 0, 0, 0 ;...
        0, sigma, -(tau+gamma10+mu+rho),0,0;...
        0,0,tau,-(theta+rho+mu), 0;...
        0,0,0,theta,-(nu+gamma30+mu+rho)];
end