function elimCostbyModel = createelimCostbyModel(list_kits_to_consider)
elimCostbyModel = table('Size',[length(list_kits_to_consider),12],...
    'VariableTypes',{'string','double','double','double','double','string','double','string','double','string','string','double'},...
    'VariableNames',{'kit','HIV','syphilis','Ct','Ng','code_err','alphaK','msgAlphaK','alphaK_K','msgAlphaK_K','msgCnnK','timeCompil'});
end
