function [ES_sictp,ES_seiiis,ES_ct,ES_ng] = singleDisES(paramTab,paramRho,mu,b)
%HIV
[res_sictp] = ode45(@(t,Y) ODE_SICTPrEP(t,Y,b,paramTab{3}.betaI,paramTab{3}.betaC,paramTab{3}.sigma,...
    paramTab{3}.theta0,paramTab{3}.p,paramTab{3}.zeta,paramTab{3}.eta,mu,paramRho.rho_h,'frequency'),...
    [1,500], ones(7,1)); ES_sictp = res_sictp.y(:,end)';

%Syphilis
[res_seiiis] = ode45(@(t,Y)  ODE_SEIIIS_v4(t,Y,paramTab{4}.beta,paramTab{4}.sigma,paramTab{4}.tau,...
    paramTab{4}.theta,paramTab{4}.gamma10,paramTab{4}.gamma30,paramTab{4}.nu,paramRho.rho_s,mu,b),...
    [1,500], ones(5,1)); ES_seiiis = res_seiiis.y(:,end)';

%Ct
[res_ct] = ode45(@(t,Y)  ODE_SEIIS_v4(t,Y,paramTab{1}.beta,paramTab{1}.nu,...
    paramTab{1}.gamma,paramTab{1}.sigma,paramTab{1}.eps,paramRho.rho_c,mu,b),...
    [1,500], ones(4,1)); ES_ct = res_ct.y(:,end)';

%Ng
[res_ng] = ode45(@(t,Y)  ODE_SEIIS_v4(t,Y,paramTab{2}.beta,paramTab{2}.nu,...
    paramTab{2}.gamma,paramTab{2}.sigma,paramTab{2}.eps,paramRho.rho_g,mu,b),...
    [1,500], ones(4,1)); ES_ng=res_ng.y(:,end)';

end

