function [alpha] = alphaSICTP(betaI,betaC,theta0,gamma0,sigma,zeta,eta,p,mu,binput,PrevThresh)


if PrevThresh==0
alpha_temp = - mu - (- betaI*eta^2 - betaI*mu^2 + eta*sigma^2 + eta^2*sigma + eta*theta0^2 + eta^2*theta0 + mu*sigma^2 +...
    mu^2*sigma + mu*theta0^2 + mu^2*theta0 + sigma*theta0^2 + sigma^2*theta0 - eta^2*((- betaI*eta^2 - betaI*mu^2 +...
    eta*sigma^2 + eta^2*sigma + eta*theta0^2 + eta^2*theta0 + mu*sigma^2 + mu^2*sigma + mu*theta0^2 + mu^2*theta0 +...
    sigma*theta0^2 + sigma^2*theta0 - betaC*p*sigma^2 - betaI*p*theta0^2 - 2*betaI*eta*mu - betaI*eta*sigma -...
    betaI*eta*theta0 - betaI*mu*sigma - betaI*mu*theta0 + 2*eta*mu*sigma + 2*eta*mu*theta0 - betaI*sigma*theta0 +...
    2*eta*sigma*theta0 + 2*mu*sigma*theta0 + betaI*eta^2*p + betaI*mu^2*p + 2*betaI*eta*mu*p - betaC*p*sigma*theta0 +...
    betaC*p*sigma^2*zeta + betaI*p*theta0^2*zeta + betaI*eta*p*sigma*zeta + betaI*eta*p*theta0*zeta +...
    betaI*mu*p*sigma*zeta + betaI*mu*p*theta0*zeta + betaC*p*sigma*theta0*zeta + betaI*p*sigma*theta0*zeta)^2/...
    ((p - 1)^2*(eta + mu + sigma)^2*(eta + mu + theta0)^2) - (4*(2*eta*mu + eta*sigma + eta*theta0 + mu*sigma +...
    mu*theta0 + sigma*theta0 + eta^2 + mu^2 - betaI*eta*p - betaI*mu*p - betaC*p*sigma - betaI*p*theta0 +...
    betaI*eta*p*zeta + betaI*mu*p*zeta + betaC*p*sigma*zeta + betaI*p*theta0*zeta)*(sigma^2*theta0^2 -...
    betaC*mu*sigma^2 - betaC*mu^2*sigma - betaI*mu*theta0^2 - betaI*mu^2*theta0 - betaC*sigma^2*theta0 -...
    betaI*sigma*theta0^2 + eta*sigma*theta0^2 + eta*sigma^2*theta0 + eta^2*sigma*theta0 + mu*sigma*theta0^2 +...
    mu*sigma^2*theta0 + mu^2*sigma*theta0 - betaC*eta*sigma^2 - betaC*eta^2*sigma - betaI*eta*theta0^2 -...
    betaI*eta^2*theta0 - 2*betaC*eta*mu*sigma - 2*betaI*eta*mu*theta0 - betaC*eta*sigma*theta0 -...
    betaI*eta*sigma*theta0 - betaC*mu*sigma*theta0 - betaI*mu*sigma*theta0 + 2*eta*mu*sigma*theta0 +...
    betaC*eta*p*sigma^2 + betaC*eta^2*p*sigma + betaI*eta*p*theta0^2 + betaI*eta^2*p*theta0 + betaC*mu*p*sigma^2 +...
    betaC*mu^2*p*sigma + betaI*mu*p*theta0^2 + betaI*mu^2*p*theta0 + 2*betaC*eta*mu*p*sigma + 2*betaI*eta*mu*p*theta0 +...
    betaC*eta*p*sigma*theta0 + betaC*mu*p*sigma*theta0 + betaC*p*sigma^2*theta0*zeta + betaI*p*sigma*theta0^2*zeta +...
    betaI*mu*p*sigma*theta0*zeta + betaI*eta*p*sigma*theta0*zeta))/((p - 1)^2*(eta + mu + sigma)^2*(eta + mu + theta0)^2))^(1/2) -...
    mu^2*((- betaI*eta^2 - betaI*mu^2 + eta*sigma^2 + eta^2*sigma + eta*theta0^2 + eta^2*theta0 + mu*sigma^2 + mu^2*sigma +...
    mu*theta0^2 + mu^2*theta0 + sigma*theta0^2 + sigma^2*theta0 - betaC*p*sigma^2 - betaI*p*theta0^2 - 2*betaI*eta*mu -...
    betaI*eta*sigma - betaI*eta*theta0 - betaI*mu*sigma - betaI*mu*theta0 + 2*eta*mu*sigma + 2*eta*mu*theta0 -...
    betaI*sigma*theta0 + 2*eta*sigma*theta0 + 2*mu*sigma*theta0 + betaI*eta^2*p + betaI*mu^2*p + 2*betaI*eta*mu*p -...
    betaC*p*sigma*theta0 + betaC*p*sigma^2*zeta + betaI*p*theta0^2*zeta + betaI*eta*p*sigma*zeta + betaI*eta*p*theta0*zeta +...
    betaI*mu*p*sigma*zeta + betaI*mu*p*theta0*zeta + betaC*p*sigma*theta0*zeta + betaI*p*sigma*theta0*zeta)^2/...
    ((p - 1)^2*(eta + mu + sigma)^2*(eta + mu + theta0)^2) - (4*(2*eta*mu + eta*sigma + eta*theta0 + mu*sigma +...
    mu*theta0 + sigma*theta0 + eta^2 + mu^2 - betaI*eta*p - betaI*mu*p - betaC*p*sigma - betaI*p*theta0 + betaI*eta*p*zeta +...
    betaI*mu*p*zeta + betaC*p*sigma*zeta + betaI*p*theta0*zeta)*(sigma^2*theta0^2 - betaC*mu*sigma^2 - betaC*mu^2*sigma -...
    betaI*mu*theta0^2 - betaI*mu^2*theta0 - betaC*sigma^2*theta0 - betaI*sigma*theta0^2 + eta*sigma*theta0^2 +...
    eta*sigma^2*theta0 + eta^2*sigma*theta0 + mu*sigma*theta0^2 + mu*sigma^2*theta0 + mu^2*sigma*theta0 -...
    betaC*eta*sigma^2 - betaC*eta^2*sigma - betaI*eta*theta0^2 - betaI*eta^2*theta0 - 2*betaC*eta*mu*sigma -...
    2*betaI*eta*mu*theta0 - betaC*eta*sigma*theta0 - betaI*eta*sigma*theta0 - betaC*mu*sigma*theta0 -...
    betaI*mu*sigma*theta0 + 2*eta*mu*sigma*theta0 + betaC*eta*p*sigma^2 + betaC*eta^2*p*sigma + betaI*eta*p*theta0^2 +...
    betaI*eta^2*p*theta0 + betaC*mu*p*sigma^2 + betaC*mu^2*p*sigma + betaI*mu*p*theta0^2 + betaI*mu^2*p*theta0 +...
    2*betaC*eta*mu*p*sigma + 2*betaI*eta*mu*p*theta0 + betaC*eta*p*sigma*theta0 + betaC*mu*p*sigma*theta0 +...
    betaC*p*sigma^2*theta0*zeta + betaI*p*sigma*theta0^2*zeta + betaI*mu*p*sigma*theta0*zeta + betaI*eta*p*sigma*theta0*zeta))/...
    ((p - 1)^2*(eta + mu + sigma)^2*(eta + mu + theta0)^2))^(1/2) - betaC*p*sigma^2 - betaI*p*theta0^2 +...
    eta^2*p*((- betaI*eta^2 - betaI*mu^2 + eta*sigma^2 + eta^2*sigma + eta*theta0^2 + eta^2*theta0 + mu*sigma^2 +...
    mu^2*sigma + mu*theta0^2 + mu^2*theta0 + sigma*theta0^2 + sigma^2*theta0 - betaC*p*sigma^2 - betaI*p*theta0^2 -...
    2*betaI*eta*mu - betaI*eta*sigma - betaI*eta*theta0 - betaI*mu*sigma - betaI*mu*theta0 + 2*eta*mu*sigma +...
    2*eta*mu*theta0 - betaI*sigma*theta0 + 2*eta*sigma*theta0 + 2*mu*sigma*theta0 + betaI*eta^2*p + betaI*mu^2*p +...
    2*betaI*eta*mu*p - betaC*p*sigma*theta0 + betaC*p*sigma^2*zeta + betaI*p*theta0^2*zeta + betaI*eta*p*sigma*zeta +...
    betaI*eta*p*theta0*zeta + betaI*mu*p*sigma*zeta + betaI*mu*p*theta0*zeta + betaC*p*sigma*theta0*zeta +...
    betaI*p*sigma*theta0*zeta)^2/((p - 1)^2*(eta + mu + sigma)^2*(eta + mu + theta0)^2) - (4*(2*eta*mu + eta*sigma +...
    eta*theta0 + mu*sigma + mu*theta0 + sigma*theta0 + eta^2 + mu^2 - betaI*eta*p - betaI*mu*p - betaC*p*sigma -...
    betaI*p*theta0 + betaI*eta*p*zeta + betaI*mu*p*zeta + betaC*p*sigma*zeta + betaI*p*theta0*zeta)*(sigma^2*theta0^2 -...
    betaC*mu*sigma^2 - betaC*mu^2*sigma - betaI*mu*theta0^2 - betaI*mu^2*theta0 - betaC*sigma^2*theta0 -...
    betaI*sigma*theta0^2 + eta*sigma*theta0^2 + eta*sigma^2*theta0 + eta^2*sigma*theta0 + mu*sigma*theta0^2 +...
    mu*sigma^2*theta0 + mu^2*sigma*theta0 - betaC*eta*sigma^2 - betaC*eta^2*sigma - betaI*eta*theta0^2 -...
    betaI*eta^2*theta0 - 2*betaC*eta*mu*sigma - 2*betaI*eta*mu*theta0 - betaC*eta*sigma*theta0 - betaI*eta*sigma*theta0 -...
    betaC*mu*sigma*theta0 - betaI*mu*sigma*theta0 + 2*eta*mu*sigma*theta0 + betaC*eta*p*sigma^2 + betaC*eta^2*p*sigma +...
    betaI*eta*p*theta0^2 + betaI*eta^2*p*theta0 + betaC*mu*p*sigma^2 + betaC*mu^2*p*sigma + betaI*mu*p*theta0^2 +...
    betaI*mu^2*p*theta0 + 2*betaC*eta*mu*p*sigma + 2*betaI*eta*mu*p*theta0 + betaC*eta*p*sigma*theta0 +...
    betaC*mu*p*sigma*theta0 + betaC*p*sigma^2*theta0*zeta + betaI*p*sigma*theta0^2*zeta + betaI*mu*p*sigma*theta0*zeta +...
    betaI*eta*p*sigma*theta0*zeta))/((p - 1)^2*(eta + mu + sigma)^2*(eta + mu + theta0)^2))^(1/2) +...
    mu^2*p*((- betaI*eta^2 - betaI*mu^2 + eta*sigma^2 + eta^2*sigma + eta*theta0^2 + eta^2*theta0 + mu*sigma^2 +...
    mu^2*sigma + mu*theta0^2 + mu^2*theta0 + sigma*theta0^2 + sigma^2*theta0 - betaC*p*sigma^2 - betaI*p*theta0^2 -...
    2*betaI*eta*mu - betaI*eta*sigma - betaI*eta*theta0 - betaI*mu*sigma - betaI*mu*theta0 + 2*eta*mu*sigma +...
    2*eta*mu*theta0 - betaI*sigma*theta0 + 2*eta*sigma*theta0 + 2*mu*sigma*theta0 + betaI*eta^2*p + betaI*mu^2*p +...
    2*betaI*eta*mu*p - betaC*p*sigma*theta0 + betaC*p*sigma^2*zeta + betaI*p*theta0^2*zeta + betaI*eta*p*sigma*zeta +...
    betaI*eta*p*theta0*zeta + betaI*mu*p*sigma*zeta + betaI*mu*p*theta0*zeta + betaC*p*sigma*theta0*zeta +...
    betaI*p*sigma*theta0*zeta)^2/((p - 1)^2*(eta + mu + sigma)^2*(eta + mu + theta0)^2) - (4*(2*eta*mu + eta*sigma +...
    eta*theta0 + mu*sigma + mu*theta0 + sigma*theta0 + eta^2 + mu^2 - betaI*eta*p - betaI*mu*p - betaC*p*sigma -...
    betaI*p*theta0 + betaI*eta*p*zeta + betaI*mu*p*zeta + betaC*p*sigma*zeta + betaI*p*theta0*zeta)*(sigma^2*theta0^2 -...
    betaC*mu*sigma^2 - betaC*mu^2*sigma - betaI*mu*theta0^2 - betaI*mu^2*theta0 - betaC*sigma^2*theta0 -...
    betaI*sigma*theta0^2 + eta*sigma*theta0^2 + eta*sigma^2*theta0 + eta^2*sigma*theta0 + mu*sigma*theta0^2 +...
    mu*sigma^2*theta0 + mu^2*sigma*theta0 - betaC*eta*sigma^2 - betaC*eta^2*sigma - betaI*eta*theta0^2 -...
    betaI*eta^2*theta0 - 2*betaC*eta*mu*sigma - 2*betaI*eta*mu*theta0 - betaC*eta*sigma*theta0 - betaI*eta*sigma*theta0 -...
    betaC*mu*sigma*theta0 - betaI*mu*sigma*theta0 + 2*eta*mu*sigma*theta0 + betaC*eta*p*sigma^2 + betaC*eta^2*p*sigma +...
    betaI*eta*p*theta0^2 + betaI*eta^2*p*theta0 + betaC*mu*p*sigma^2 + betaC*mu^2*p*sigma + betaI*mu*p*theta0^2 +...
    betaI*mu^2*p*theta0 + 2*betaC*eta*mu*p*sigma + 2*betaI*eta*mu*p*theta0 + betaC*eta*p*sigma*theta0 +...
    betaC*mu*p*sigma*theta0 + betaC*p*sigma^2*theta0*zeta + betaI*p*sigma*theta0^2*zeta + betaI*mu*p*sigma*theta0*zeta +...
    betaI*eta*p*sigma*theta0*zeta))/((p - 1)^2*(eta + mu + sigma)^2*(eta + mu + theta0)^2))^(1/2) - 2*betaI*eta*mu -...
    betaI*eta*sigma - betaI*eta*theta0 - betaI*mu*sigma - betaI*mu*theta0 + 2*eta*mu*sigma + 2*eta*mu*theta0 -...
    betaI*sigma*theta0 + 2*eta*sigma*theta0 + 2*mu*sigma*theta0 - 2*eta*mu*((- betaI*eta^2 - betaI*mu^2 + eta*sigma^2 +...
    eta^2*sigma + eta*theta0^2 + eta^2*theta0 + mu*sigma^2 + mu^2*sigma + mu*theta0^2 + mu^2*theta0 + sigma*theta0^2 +...
    sigma^2*theta0 - betaC*p*sigma^2 - betaI*p*theta0^2 - 2*betaI*eta*mu - betaI*eta*sigma - betaI*eta*theta0 -...
    betaI*mu*sigma - betaI*mu*theta0 + 2*eta*mu*sigma + 2*eta*mu*theta0 - betaI*sigma*theta0 + 2*eta*sigma*theta0 +...
    2*mu*sigma*theta0 + betaI*eta^2*p + betaI*mu^2*p + 2*betaI*eta*mu*p - betaC*p*sigma*theta0 + betaC*p*sigma^2*zeta +...
    betaI*p*theta0^2*zeta + betaI*eta*p*sigma*zeta + betaI*eta*p*theta0*zeta + betaI*mu*p*sigma*zeta + betaI*mu*p*theta0*zeta +...
    betaC*p*sigma*theta0*zeta + betaI*p*sigma*theta0*zeta)^2/((p - 1)^2*(eta + mu + sigma)^2*(eta + mu + theta0)^2) -...
    (4*(2*eta*mu + eta*sigma + eta*theta0 + mu*sigma + mu*theta0 + sigma*theta0 + eta^2 + mu^2 - betaI*eta*p -...
    betaI*mu*p - betaC*p*sigma - betaI*p*theta0 + betaI*eta*p*zeta + betaI*mu*p*zeta + betaC*p*sigma*zeta +...
    betaI*p*theta0*zeta)*(sigma^2*theta0^2 - betaC*mu*sigma^2 - betaC*mu^2*sigma - betaI*mu*theta0^2 - betaI*mu^2*theta0 -...
    betaC*sigma^2*theta0 - betaI*sigma*theta0^2 + eta*sigma*theta0^2 + eta*sigma^2*theta0 + eta^2*sigma*theta0 +...
    mu*sigma*theta0^2 + mu*sigma^2*theta0 + mu^2*sigma*theta0 - betaC*eta*sigma^2 - betaC*eta^2*sigma -...
    betaI*eta*theta0^2 - betaI*eta^2*theta0 - 2*betaC*eta*mu*sigma - 2*betaI*eta*mu*theta0 - betaC*eta*sigma*theta0 -...
    betaI*eta*sigma*theta0 - betaC*mu*sigma*theta0 - betaI*mu*sigma*theta0 + 2*eta*mu*sigma*theta0 + betaC*eta*p*sigma^2 +...
    betaC*eta^2*p*sigma + betaI*eta*p*theta0^2 + betaI*eta^2*p*theta0 + betaC*mu*p*sigma^2 + betaC*mu^2*p*sigma +...
    betaI*mu*p*theta0^2 + betaI*mu^2*p*theta0 + 2*betaC*eta*mu*p*sigma + 2*betaI*eta*mu*p*theta0 + betaC*eta*p*sigma*theta0 +...
    betaC*mu*p*sigma*theta0 + betaC*p*sigma^2*theta0*zeta + betaI*p*sigma*theta0^2*zeta + betaI*mu*p*sigma*theta0*zeta +...
    betaI*eta*p*sigma*theta0*zeta))/((p - 1)^2*(eta + mu + sigma)^2*(eta + mu + theta0)^2))^(1/2) -...
    eta*sigma*((- betaI*eta^2 - betaI*mu^2 + eta*sigma^2 + eta^2*sigma + eta*theta0^2 + eta^2*theta0 +...
    mu*sigma^2 + mu^2*sigma + mu*theta0^2 + mu^2*theta0 + sigma*theta0^2 + sigma^2*theta0 - betaC*p*sigma^2 -...
    betaI*p*theta0^2 - 2*betaI*eta*mu - betaI*eta*sigma - betaI*eta*theta0 - betaI*mu*sigma - betaI*mu*theta0 +...
    2*eta*mu*sigma + 2*eta*mu*theta0 - betaI*sigma*theta0 + 2*eta*sigma*theta0 + 2*mu*sigma*theta0 + betaI*eta^2*p +...
    betaI*mu^2*p + 2*betaI*eta*mu*p - betaC*p*sigma*theta0 + betaC*p*sigma^2*zeta + betaI*p*theta0^2*zeta +...
    betaI*eta*p*sigma*zeta + betaI*eta*p*theta0*zeta + betaI*mu*p*sigma*zeta + betaI*mu*p*theta0*zeta +...
    betaC*p*sigma*theta0*zeta + betaI*p*sigma*theta0*zeta)^2/((p - 1)^2*(eta + mu + sigma)^2*(eta + mu + theta0)^2) -...
    (4*(2*eta*mu + eta*sigma + eta*theta0 + mu*sigma + mu*theta0 + sigma*theta0 + eta^2 + mu^2 - betaI*eta*p -...
    betaI*mu*p - betaC*p*sigma - betaI*p*theta0 + betaI*eta*p*zeta + betaI*mu*p*zeta + betaC*p*sigma*zeta +...
    betaI*p*theta0*zeta)*(sigma^2*theta0^2 - betaC*mu*sigma^2 - betaC*mu^2*sigma - betaI*mu*theta0^2 - betaI*mu^2*theta0 -...
    betaC*sigma^2*theta0 - betaI*sigma*theta0^2 + eta*sigma*theta0^2 + eta*sigma^2*theta0 + eta^2*sigma*theta0 +...
    mu*sigma*theta0^2 + mu*sigma^2*theta0 + mu^2*sigma*theta0 - betaC*eta*sigma^2 - betaC*eta^2*sigma - betaI*eta*theta0^2 -...
    betaI*eta^2*theta0 - 2*betaC*eta*mu*sigma - 2*betaI*eta*mu*theta0 - betaC*eta*sigma*theta0 - betaI*eta*sigma*theta0 -...
    betaC*mu*sigma*theta0 - betaI*mu*sigma*theta0 + 2*eta*mu*sigma*theta0 + betaC*eta*p*sigma^2 + betaC*eta^2*p*sigma +...
    betaI*eta*p*theta0^2 + betaI*eta^2*p*theta0 + betaC*mu*p*sigma^2 + betaC*mu^2*p*sigma + betaI*mu*p*theta0^2 +...
    betaI*mu^2*p*theta0 + 2*betaC*eta*mu*p*sigma + 2*betaI*eta*mu*p*theta0 + betaC*eta*p*sigma*theta0 +...
    betaC*mu*p*sigma*theta0 + betaC*p*sigma^2*theta0*zeta + betaI*p*sigma*theta0^2*zeta + betaI*mu*p*sigma*theta0*zeta +...
    betaI*eta*p*sigma*theta0*zeta))/((p - 1)^2*(eta + mu + sigma)^2*(eta + mu + theta0)^2))^(1/2) -...
    eta*theta0*((- betaI*eta^2 - betaI*mu^2 + eta*sigma^2 + eta^2*sigma + eta*theta0^2 + eta^2*theta0 + mu*sigma^2 +...
    mu^2*sigma + mu*theta0^2 + mu^2*theta0 + sigma*theta0^2 + sigma^2*theta0 - betaC*p*sigma^2 - betaI*p*theta0^2 -...
    2*betaI*eta*mu - betaI*eta*sigma - betaI*eta*theta0 - betaI*mu*sigma - betaI*mu*theta0 + 2*eta*mu*sigma +...
    2*eta*mu*theta0 - betaI*sigma*theta0 + 2*eta*sigma*theta0 + 2*mu*sigma*theta0 + betaI*eta^2*p + betaI*mu^2*p +...
    2*betaI*eta*mu*p - betaC*p*sigma*theta0 + betaC*p*sigma^2*zeta + betaI*p*theta0^2*zeta + betaI*eta*p*sigma*zeta +...
    betaI*eta*p*theta0*zeta + betaI*mu*p*sigma*zeta + betaI*mu*p*theta0*zeta + betaC*p*sigma*theta0*zeta +...
    betaI*p*sigma*theta0*zeta)^2/((p - 1)^2*(eta + mu + sigma)^2*(eta + mu + theta0)^2) - (4*(2*eta*mu + eta*sigma +...
    eta*theta0 + mu*sigma + mu*theta0 + sigma*theta0 + eta^2 + mu^2 - betaI*eta*p - betaI*mu*p - betaC*p*sigma -...
    betaI*p*theta0 + betaI*eta*p*zeta + betaI*mu*p*zeta + betaC*p*sigma*zeta + betaI*p*theta0*zeta)*(sigma^2*theta0^2 -...
    betaC*mu*sigma^2 - betaC*mu^2*sigma - betaI*mu*theta0^2 - betaI*mu^2*theta0 - betaC*sigma^2*theta0 -...
    betaI*sigma*theta0^2 + eta*sigma*theta0^2 + eta*sigma^2*theta0 + eta^2*sigma*theta0 + mu*sigma*theta0^2 +...
    mu*sigma^2*theta0 + mu^2*sigma*theta0 - betaC*eta*sigma^2 - betaC*eta^2*sigma - betaI*eta*theta0^2 -...
    betaI*eta^2*theta0 - 2*betaC*eta*mu*sigma - 2*betaI*eta*mu*theta0 - betaC*eta*sigma*theta0 - betaI*eta*sigma*theta0 -...
    betaC*mu*sigma*theta0 - betaI*mu*sigma*theta0 + 2*eta*mu*sigma*theta0 + betaC*eta*p*sigma^2 +...
    betaC*eta^2*p*sigma + betaI*eta*p*theta0^2 + betaI*eta^2*p*theta0 + betaC*mu*p*sigma^2 + betaC*mu^2*p*sigma +...
    betaI*mu*p*theta0^2 + betaI*mu^2*p*theta0 + 2*betaC*eta*mu*p*sigma + 2*betaI*eta*mu*p*theta0 + betaC*eta*p*sigma*theta0 +...
    betaC*mu*p*sigma*theta0 + betaC*p*sigma^2*theta0*zeta + betaI*p*sigma*theta0^2*zeta + betaI*mu*p*sigma*theta0*zeta +...
    betaI*eta*p*sigma*theta0*zeta))/((p - 1)^2*(eta + mu + sigma)^2*(eta + mu + theta0)^2))^(1/2) -...
    mu*sigma*((- betaI*eta^2 - betaI*mu^2 + eta*sigma^2 + eta^2*sigma + eta*theta0^2 + eta^2*theta0 + mu*sigma^2 +...
    mu^2*sigma + mu*theta0^2 + mu^2*theta0 + sigma*theta0^2 + sigma^2*theta0 - betaC*p*sigma^2 - betaI*p*theta0^2 -...
    2*betaI*eta*mu - betaI*eta*sigma - betaI*eta*theta0 - betaI*mu*sigma - betaI*mu*theta0 + 2*eta*mu*sigma +...
    2*eta*mu*theta0 - betaI*sigma*theta0 + 2*eta*sigma*theta0 + 2*mu*sigma*theta0 + betaI*eta^2*p + betaI*mu^2*p +...
    2*betaI*eta*mu*p - betaC*p*sigma*theta0 + betaC*p*sigma^2*zeta + betaI*p*theta0^2*zeta + betaI*eta*p*sigma*zeta +...
    betaI*eta*p*theta0*zeta + betaI*mu*p*sigma*zeta + betaI*mu*p*theta0*zeta + betaC*p*sigma*theta0*zeta +...
    betaI*p*sigma*theta0*zeta)^2/((p - 1)^2*(eta + mu + sigma)^2*(eta + mu + theta0)^2) - (4*(2*eta*mu + eta*sigma +...
    eta*theta0 + mu*sigma + mu*theta0 + sigma*theta0 + eta^2 + mu^2 - betaI*eta*p - betaI*mu*p - betaC*p*sigma -...
    betaI*p*theta0 + betaI*eta*p*zeta + betaI*mu*p*zeta + betaC*p*sigma*zeta + betaI*p*theta0*zeta)*(sigma^2*theta0^2 -...
    betaC*mu*sigma^2 - betaC*mu^2*sigma - betaI*mu*theta0^2 - betaI*mu^2*theta0 - betaC*sigma^2*theta0 -...
    betaI*sigma*theta0^2 + eta*sigma*theta0^2 + eta*sigma^2*theta0 + eta^2*sigma*theta0 + mu*sigma*theta0^2 +...
    mu*sigma^2*theta0 + mu^2*sigma*theta0 - betaC*eta*sigma^2 - betaC*eta^2*sigma - betaI*eta*theta0^2 -...
    betaI*eta^2*theta0 - 2*betaC*eta*mu*sigma - 2*betaI*eta*mu*theta0 - betaC*eta*sigma*theta0 - betaI*eta*sigma*theta0 -...
    betaC*mu*sigma*theta0 - betaI*mu*sigma*theta0 + 2*eta*mu*sigma*theta0 + betaC*eta*p*sigma^2 + betaC*eta^2*p*sigma +...
    betaI*eta*p*theta0^2 + betaI*eta^2*p*theta0 + betaC*mu*p*sigma^2 + betaC*mu^2*p*sigma + betaI*mu*p*theta0^2 +...
    betaI*mu^2*p*theta0 + 2*betaC*eta*mu*p*sigma + 2*betaI*eta*mu*p*theta0 + betaC*eta*p*sigma*theta0 +...
    betaC*mu*p*sigma*theta0 + betaC*p*sigma^2*theta0*zeta + betaI*p*sigma*theta0^2*zeta + betaI*mu*p*sigma*theta0*zeta +...
    betaI*eta*p*sigma*theta0*zeta))/((p - 1)^2*(eta + mu + sigma)^2*(eta + mu + theta0)^2))^(1/2) -...
    mu*theta0*((- betaI*eta^2 - betaI*mu^2 + eta*sigma^2 + eta^2*sigma + eta*theta0^2 + eta^2*theta0 + mu*sigma^2 +...
    mu^2*sigma + mu*theta0^2 + mu^2*theta0 + sigma*theta0^2 + sigma^2*theta0 - betaC*p*sigma^2 - betaI*p*theta0^2 -...
    2*betaI*eta*mu - betaI*eta*sigma - betaI*eta*theta0 - betaI*mu*sigma - betaI*mu*theta0 + 2*eta*mu*sigma +...
    2*eta*mu*theta0 - betaI*sigma*theta0 + 2*eta*sigma*theta0 + 2*mu*sigma*theta0 + betaI*eta^2*p + betaI*mu^2*p +...
    2*betaI*eta*mu*p - betaC*p*sigma*theta0 + betaC*p*sigma^2*zeta + betaI*p*theta0^2*zeta + betaI*eta*p*sigma*zeta +...
    betaI*eta*p*theta0*zeta + betaI*mu*p*sigma*zeta + betaI*mu*p*theta0*zeta + betaC*p*sigma*theta0*zeta +...
    betaI*p*sigma*theta0*zeta)^2/((p - 1)^2*(eta + mu + sigma)^2*(eta + mu + theta0)^2) - (4*(2*eta*mu + eta*sigma +...
    eta*theta0 + mu*sigma + mu*theta0 + sigma*theta0 + eta^2 + mu^2 - betaI*eta*p - betaI*mu*p - betaC*p*sigma - ...
    betaI*p*theta0 + betaI*eta*p*zeta + betaI*mu*p*zeta + betaC*p*sigma*zeta + betaI*p*theta0*zeta)*(sigma^2*theta0^2 -...
    betaC*mu*sigma^2 - betaC*mu^2*sigma - betaI*mu*theta0^2 - betaI*mu^2*theta0 - betaC*sigma^2*theta0 -...
    betaI*sigma*theta0^2 + eta*sigma*theta0^2 + eta*sigma^2*theta0 + eta^2*sigma*theta0 + mu*sigma*theta0^2 +...
    mu*sigma^2*theta0 + mu^2*sigma*theta0 - betaC*eta*sigma^2 - betaC*eta^2*sigma - betaI*eta*theta0^2 -...
    betaI*eta^2*theta0 - 2*betaC*eta*mu*sigma - 2*betaI*eta*mu*theta0 - betaC*eta*sigma*theta0 - betaI*eta*sigma*theta0 -...
    betaC*mu*sigma*theta0 - betaI*mu*sigma*theta0 + 2*eta*mu*sigma*theta0 + betaC*eta*p*sigma^2 + betaC*eta^2*p*sigma +...
    betaI*eta*p*theta0^2 + betaI*eta^2*p*theta0 + betaC*mu*p*sigma^2 + betaC*mu^2*p*sigma + betaI*mu*p*theta0^2 +...
    betaI*mu^2*p*theta0 + 2*betaC*eta*mu*p*sigma + 2*betaI*eta*mu*p*theta0 + betaC*eta*p*sigma*theta0 +...
    betaC*mu*p*sigma*theta0 + betaC*p*sigma^2*theta0*zeta + betaI*p*sigma*theta0^2*zeta + betaI*mu*p*sigma*theta0*zeta +...
    betaI*eta*p*sigma*theta0*zeta))/((p - 1)^2*(eta + mu + sigma)^2*(eta + mu + theta0)^2))^(1/2) -...
    sigma*theta0*((- betaI*eta^2 - betaI*mu^2 + eta*sigma^2 + eta^2*sigma + eta*theta0^2 + eta^2*theta0 +...
    mu*sigma^2 + mu^2*sigma + mu*theta0^2 + mu^2*theta0 + sigma*theta0^2 + sigma^2*theta0 - betaC*p*sigma^2 -...
    betaI*p*theta0^2 - 2*betaI*eta*mu - betaI*eta*sigma - betaI*eta*theta0 - betaI*mu*sigma - betaI*mu*theta0 + ...
    2*eta*mu*sigma + 2*eta*mu*theta0 - betaI*sigma*theta0 + 2*eta*sigma*theta0 + 2*mu*sigma*theta0 + betaI*eta^2*p +...
    betaI*mu^2*p + 2*betaI*eta*mu*p - betaC*p*sigma*theta0 + betaC*p*sigma^2*zeta + betaI*p*theta0^2*zeta +...
    betaI*eta*p*sigma*zeta + betaI*eta*p*theta0*zeta + betaI*mu*p*sigma*zeta + betaI*mu*p*theta0*zeta +...
    betaC*p*sigma*theta0*zeta + betaI*p*sigma*theta0*zeta)^2/((p - 1)^2*(eta + mu + sigma)^2*(eta + mu + theta0)^2) -...
    (4*(2*eta*mu + eta*sigma + eta*theta0 + mu*sigma + mu*theta0 + sigma*theta0 + eta^2 + mu^2 - betaI*eta*p -...
    betaI*mu*p - betaC*p*sigma - betaI*p*theta0 + betaI*eta*p*zeta + betaI*mu*p*zeta + betaC*p*sigma*zeta +...
    betaI*p*theta0*zeta)*(sigma^2*theta0^2 - betaC*mu*sigma^2 - betaC*mu^2*sigma - betaI*mu*theta0^2 -...
    betaI*mu^2*theta0 - betaC*sigma^2*theta0 - betaI*sigma*theta0^2 + eta*sigma*theta0^2 + eta*sigma^2*theta0 +...
    eta^2*sigma*theta0 + mu*sigma*theta0^2 + mu*sigma^2*theta0 + mu^2*sigma*theta0 - betaC*eta*sigma^2 -...
    betaC*eta^2*sigma - betaI*eta*theta0^2 - betaI*eta^2*theta0 - 2*betaC*eta*mu*sigma - 2*betaI*eta*mu*theta0 -...
    betaC*eta*sigma*theta0 - betaI*eta*sigma*theta0 - betaC*mu*sigma*theta0 - betaI*mu*sigma*theta0 +...
    2*eta*mu*sigma*theta0 + betaC*eta*p*sigma^2 + betaC*eta^2*p*sigma + betaI*eta*p*theta0^2 + betaI*eta^2*p*theta0 +...
    betaC*mu*p*sigma^2 + betaC*mu^2*p*sigma + betaI*mu*p*theta0^2 + betaI*mu^2*p*theta0 + 2*betaC*eta*mu*p*sigma +...
    2*betaI*eta*mu*p*theta0 + betaC*eta*p*sigma*theta0 + betaC*mu*p*sigma*theta0 + betaC*p*sigma^2*theta0*zeta +...
    betaI*p*sigma*theta0^2*zeta + betaI*mu*p*sigma*theta0*zeta + betaI*eta*p*sigma*theta0*zeta))/((p - 1)^2*(eta +...
    mu + sigma)^2*(eta + mu + theta0)^2))^(1/2) + betaI*eta^2*p + betaI*mu^2*p + 2*betaI*eta*mu*p - betaC*p*sigma*theta0 +...
    2*eta*mu*p*((- betaI*eta^2 - betaI*mu^2 + eta*sigma^2 + eta^2*sigma + eta*theta0^2 + eta^2*theta0 + mu*sigma^2 +...
    mu^2*sigma + mu*theta0^2 + mu^2*theta0 + sigma*theta0^2 + sigma^2*theta0 - betaC*p*sigma^2 - betaI*p*theta0^2 -...
    2*betaI*eta*mu - betaI*eta*sigma - betaI*eta*theta0 - betaI*mu*sigma - betaI*mu*theta0 + 2*eta*mu*sigma +...
    2*eta*mu*theta0 - betaI*sigma*theta0 + 2*eta*sigma*theta0 + 2*mu*sigma*theta0 + betaI*eta^2*p + betaI*mu^2*p +...
    2*betaI*eta*mu*p - betaC*p*sigma*theta0 + betaC*p*sigma^2*zeta + betaI*p*theta0^2*zeta + betaI*eta*p*sigma*zeta +...
    betaI*eta*p*theta0*zeta + betaI*mu*p*sigma*zeta + betaI*mu*p*theta0*zeta + betaC*p*sigma*theta0*zeta +...
    betaI*p*sigma*theta0*zeta)^2/((p - 1)^2*(eta + mu + sigma)^2*(eta + mu + theta0)^2) - (4*(2*eta*mu +...
    eta*sigma + eta*theta0 + mu*sigma + mu*theta0 + sigma*theta0 + eta^2 + mu^2 - betaI*eta*p - betaI*mu*p -...
    betaC*p*sigma - betaI*p*theta0 + betaI*eta*p*zeta + betaI*mu*p*zeta + betaC*p*sigma*zeta + betaI*p*theta0*zeta)*...
    (sigma^2*theta0^2 - betaC*mu*sigma^2 - betaC*mu^2*sigma - betaI*mu*theta0^2 - betaI*mu^2*theta0 -...
    betaC*sigma^2*theta0 - betaI*sigma*theta0^2 + eta*sigma*theta0^2 + eta*sigma^2*theta0 + eta^2*sigma*theta0 +...
    mu*sigma*theta0^2 + mu*sigma^2*theta0 + mu^2*sigma*theta0 - betaC*eta*sigma^2 - betaC*eta^2*sigma -...
    betaI*eta*theta0^2 - betaI*eta^2*theta0 - 2*betaC*eta*mu*sigma - 2*betaI*eta*mu*theta0 - betaC*eta*sigma*theta0 -...
    betaI*eta*sigma*theta0 - betaC*mu*sigma*theta0 - betaI*mu*sigma*theta0 + 2*eta*mu*sigma*theta0 + betaC*eta*p*sigma^2 +...
    betaC*eta^2*p*sigma + betaI*eta*p*theta0^2 + betaI*eta^2*p*theta0 + betaC*mu*p*sigma^2 + betaC*mu^2*p*sigma +...
    betaI*mu*p*theta0^2 + betaI*mu^2*p*theta0 + 2*betaC*eta*mu*p*sigma + 2*betaI*eta*mu*p*theta0 +...
    betaC*eta*p*sigma*theta0 + betaC*mu*p*sigma*theta0 + betaC*p*sigma^2*theta0*zeta + betaI*p*sigma*theta0^2*zeta +...
    betaI*mu*p*sigma*theta0*zeta + betaI*eta*p*sigma*theta0*zeta))/((p - 1)^2*(eta + mu + sigma)^2*(eta +...
    mu + theta0)^2))^(1/2) + eta*p*sigma*((- betaI*eta^2 - betaI*mu^2 + eta*sigma^2 + eta^2*sigma + eta*theta0^2 +...
    eta^2*theta0 + mu*sigma^2 + mu^2*sigma + mu*theta0^2 + mu^2*theta0 + sigma*theta0^2 + sigma^2*theta0 -...
    betaC*p*sigma^2 - betaI*p*theta0^2 - 2*betaI*eta*mu - betaI*eta*sigma - betaI*eta*theta0 - betaI*mu*sigma -...
    betaI*mu*theta0 + 2*eta*mu*sigma + 2*eta*mu*theta0 - betaI*sigma*theta0 + 2*eta*sigma*theta0 +...
    2*mu*sigma*theta0 + betaI*eta^2*p + betaI*mu^2*p + 2*betaI*eta*mu*p - betaC*p*sigma*theta0 + betaC*p*sigma^2*zeta +...
    betaI*p*theta0^2*zeta + betaI*eta*p*sigma*zeta + betaI*eta*p*theta0*zeta + betaI*mu*p*sigma*zeta +...
    betaI*mu*p*theta0*zeta + betaC*p*sigma*theta0*zeta + betaI*p*sigma*theta0*zeta)^2/((p - 1)^2*(eta + mu +...
    sigma)^2*(eta + mu + theta0)^2) - (4*(2*eta*mu + eta*sigma + eta*theta0 + mu*sigma + mu*theta0 + sigma*theta0 +...
    eta^2 + mu^2 - betaI*eta*p - betaI*mu*p - betaC*p*sigma - betaI*p*theta0 + betaI*eta*p*zeta + betaI*mu*p*zeta +...
    betaC*p*sigma*zeta + betaI*p*theta0*zeta)*(sigma^2*theta0^2 - betaC*mu*sigma^2 - betaC*mu^2*sigma -...
    betaI*mu*theta0^2 - betaI*mu^2*theta0 - betaC*sigma^2*theta0 - betaI*sigma*theta0^2 + eta*sigma*theta0^2 +...
    eta*sigma^2*theta0 + eta^2*sigma*theta0 + mu*sigma*theta0^2 + mu*sigma^2*theta0 + mu^2*sigma*theta0 -...
    betaC*eta*sigma^2 - betaC*eta^2*sigma - betaI*eta*theta0^2 - betaI*eta^2*theta0 - 2*betaC*eta*mu*sigma -...
    2*betaI*eta*mu*theta0 - betaC*eta*sigma*theta0 - betaI*eta*sigma*theta0 - betaC*mu*sigma*theta0 -...
    betaI*mu*sigma*theta0 + 2*eta*mu*sigma*theta0 + betaC*eta*p*sigma^2 + betaC*eta^2*p*sigma + betaI*eta*p*theta0^2 +...
    betaI*eta^2*p*theta0 + betaC*mu*p*sigma^2 + betaC*mu^2*p*sigma + betaI*mu*p*theta0^2 + betaI*mu^2*p*theta0 +...
    2*betaC*eta*mu*p*sigma + 2*betaI*eta*mu*p*theta0 + betaC*eta*p*sigma*theta0 + betaC*mu*p*sigma*theta0 + ...
    betaC*p*sigma^2*theta0*zeta + betaI*p*sigma*theta0^2*zeta + betaI*mu*p*sigma*theta0*zeta +...
    betaI*eta*p*sigma*theta0*zeta))/((p - 1)^2*(eta + mu + sigma)^2*(eta + mu + theta0)^2))^(1/2) +...
    eta*p*theta0*((- betaI*eta^2 - betaI*mu^2 + eta*sigma^2 + eta^2*sigma + eta*theta0^2 + eta^2*theta0 +...
    mu*sigma^2 + mu^2*sigma + mu*theta0^2 + mu^2*theta0 + sigma*theta0^2 + sigma^2*theta0 - betaC*p*sigma^2 -...
    betaI*p*theta0^2 - 2*betaI*eta*mu - betaI*eta*sigma - betaI*eta*theta0 - betaI*mu*sigma - betaI*mu*theta0 +...
    2*eta*mu*sigma + 2*eta*mu*theta0 - betaI*sigma*theta0 + 2*eta*sigma*theta0 + 2*mu*sigma*theta0 + betaI*eta^2*p +...
    betaI*mu^2*p + 2*betaI*eta*mu*p - betaC*p*sigma*theta0 + betaC*p*sigma^2*zeta + betaI*p*theta0^2*zeta +...
    betaI*eta*p*sigma*zeta + betaI*eta*p*theta0*zeta + betaI*mu*p*sigma*zeta + betaI*mu*p*theta0*zeta +...
    betaC*p*sigma*theta0*zeta + betaI*p*sigma*theta0*zeta)^2/((p - 1)^2*(eta + mu + sigma)^2*(eta + mu + theta0)^2) -...
    (4*(2*eta*mu + eta*sigma + eta*theta0 + mu*sigma + mu*theta0 + sigma*theta0 + eta^2 + mu^2 - betaI*eta*p -...
    betaI*mu*p - betaC*p*sigma - betaI*p*theta0 + betaI*eta*p*zeta + betaI*mu*p*zeta + betaC*p*sigma*zeta +...
    betaI*p*theta0*zeta)*(sigma^2*theta0^2 - betaC*mu*sigma^2 - betaC*mu^2*sigma - betaI*mu*theta0^2 -...
    betaI*mu^2*theta0 - betaC*sigma^2*theta0 - betaI*sigma*theta0^2 + eta*sigma*theta0^2 + eta*sigma^2*theta0 +...
    eta^2*sigma*theta0 + mu*sigma*theta0^2 + mu*sigma^2*theta0 + mu^2*sigma*theta0 - betaC*eta*sigma^2 - betaC*eta^2*sigma - betaI*eta*theta0^2 - betaI*eta^2*theta0 - 2*betaC*eta*mu*sigma - 2*betaI*eta*mu*theta0 - betaC*eta*sigma*theta0 - betaI*eta*sigma*theta0 - betaC*mu*sigma*theta0 - betaI*mu*sigma*theta0 + 2*eta*mu*sigma*theta0 + betaC*eta*p*sigma^2 + betaC*eta^2*p*sigma + betaI*eta*p*theta0^2 + betaI*eta^2*p*theta0 + betaC*mu*p*sigma^2 + betaC*mu^2*p*sigma + betaI*mu*p*theta0^2 + betaI*mu^2*p*theta0 + 2*betaC*eta*mu*p*sigma + 2*betaI*eta*mu*p*theta0 + betaC*eta*p*sigma*theta0 + betaC*mu*p*sigma*theta0 + betaC*p*sigma^2*theta0*zeta + betaI*p*sigma*theta0^2*zeta + betaI*mu*p*sigma*theta0*zeta + betaI*eta*p*sigma*theta0*zeta))/((p - 1)^2*(eta + mu + sigma)^2*(eta + mu + theta0)^2))^(1/2) + mu*p*sigma*((- betaI*eta^2 - betaI*mu^2 + eta*sigma^2 + eta^2*sigma + eta*theta0^2 + eta^2*theta0 + mu*sigma^2 + mu^2*sigma + mu*theta0^2 + mu^2*theta0 + sigma*theta0^2 + sigma^2*theta0 - betaC*p*sigma^2 - betaI*p*theta0^2 - 2*betaI*eta*mu - betaI*eta*sigma - betaI*eta*theta0 - betaI*mu*sigma - betaI*mu*theta0 + 2*eta*mu*sigma + 2*eta*mu*theta0 - betaI*sigma*theta0 + 2*eta*sigma*theta0 + 2*mu*sigma*theta0 + betaI*eta^2*p + betaI*mu^2*p + 2*betaI*eta*mu*p - betaC*p*sigma*theta0 + betaC*p*sigma^2*zeta + betaI*p*theta0^2*zeta + betaI*eta*p*sigma*zeta + betaI*eta*p*theta0*zeta + betaI*mu*p*sigma*zeta + betaI*mu*p*theta0*zeta + betaC*p*sigma*theta0*zeta + betaI*p*sigma*theta0*zeta)^2/((p - 1)^2*(eta + mu + sigma)^2*(eta + mu + theta0)^2) - (4*(2*eta*mu + eta*sigma + eta*theta0 + mu*sigma + mu*theta0 + sigma*theta0 + eta^2 + mu^2 - betaI*eta*p - betaI*mu*p - betaC*p*sigma - betaI*p*theta0 + betaI*eta*p*zeta + betaI*mu*p*zeta + betaC*p*sigma*zeta + betaI*p*theta0*zeta)*(sigma^2*theta0^2 - betaC*mu*sigma^2 - betaC*mu^2*sigma - betaI*mu*theta0^2 - betaI*mu^2*theta0 - betaC*sigma^2*theta0 - betaI*sigma*theta0^2 + eta*sigma*theta0^2 + eta*sigma^2*theta0 + eta^2*sigma*theta0 + mu*sigma*theta0^2 + mu*sigma^2*theta0 + mu^2*sigma*theta0 - betaC*eta*sigma^2 - betaC*eta^2*sigma - betaI*eta*theta0^2 - betaI*eta^2*theta0 - 2*betaC*eta*mu*sigma - 2*betaI*eta*mu*theta0 - betaC*eta*sigma*theta0 - betaI*eta*sigma*theta0 - betaC*mu*sigma*theta0 - betaI*mu*sigma*theta0 + 2*eta*mu*sigma*theta0 + betaC*eta*p*sigma^2 + betaC*eta^2*p*sigma + betaI*eta*p*theta0^2 + betaI*eta^2*p*theta0 + betaC*mu*p*sigma^2 + betaC*mu^2*p*sigma + betaI*mu*p*theta0^2 + betaI*mu^2*p*theta0 + 2*betaC*eta*mu*p*sigma + 2*betaI*eta*mu*p*theta0 + betaC*eta*p*sigma*theta0 + betaC*mu*p*sigma*theta0 + betaC*p*sigma^2*theta0*zeta + betaI*p*sigma*theta0^2*zeta + betaI*mu*p*sigma*theta0*zeta + betaI*eta*p*sigma*theta0*zeta))/((p - 1)^2*(eta + mu + sigma)^2*(eta + mu + theta0)^2))^(1/2) + mu*p*theta0*((- betaI*eta^2 - betaI*mu^2 + eta*sigma^2 + eta^2*sigma + eta*theta0^2 + eta^2*theta0 + mu*sigma^2 + mu^2*sigma + mu*theta0^2 + mu^2*theta0 + sigma*theta0^2 + sigma^2*theta0 - betaC*p*sigma^2 - betaI*p*theta0^2 - 2*betaI*eta*mu - betaI*eta*sigma - betaI*eta*theta0 - betaI*mu*sigma - betaI*mu*theta0 + 2*eta*mu*sigma + 2*eta*mu*theta0 - betaI*sigma*theta0 + 2*eta*sigma*theta0 + 2*mu*sigma*theta0 + betaI*eta^2*p + betaI*mu^2*p + 2*betaI*eta*mu*p - betaC*p*sigma*theta0 + betaC*p*sigma^2*zeta + betaI*p*theta0^2*zeta + betaI*eta*p*sigma*zeta + betaI*eta*p*theta0*zeta + betaI*mu*p*sigma*zeta + betaI*mu*p*theta0*zeta + betaC*p*sigma*theta0*zeta + betaI*p*sigma*theta0*zeta)^2/((p - 1)^2*(eta + mu + sigma)^2*(eta + mu + theta0)^2) - (4*(2*eta*mu + eta*sigma + eta*theta0 + mu*sigma + mu*theta0 + sigma*theta0 + eta^2 + mu^2 - betaI*eta*p - betaI*mu*p - betaC*p*sigma - betaI*p*theta0 + betaI*eta*p*zeta + betaI*mu*p*zeta + betaC*p*sigma*zeta + betaI*p*theta0*zeta)*(sigma^2*theta0^2 - betaC*mu*sigma^2 - betaC*mu^2*sigma - betaI*mu*theta0^2 - betaI*mu^2*theta0 - betaC*sigma^2*theta0 - betaI*sigma*theta0^2 + eta*sigma*theta0^2 + eta*sigma^2*theta0 + eta^2*sigma*theta0 + mu*sigma*theta0^2 + mu*sigma^2*theta0 + mu^2*sigma*theta0 - betaC*eta*sigma^2 - betaC*eta^2*sigma - betaI*eta*theta0^2 - betaI*eta^2*theta0 - 2*betaC*eta*mu*sigma - 2*betaI*eta*mu*theta0 - betaC*eta*sigma*theta0 - betaI*eta*sigma*theta0 - betaC*mu*sigma*theta0 - betaI*mu*sigma*theta0 + 2*eta*mu*sigma*theta0 + betaC*eta*p*sigma^2 + betaC*eta^2*p*sigma + betaI*eta*p*theta0^2 + betaI*eta^2*p*theta0 + betaC*mu*p*sigma^2 + betaC*mu^2*p*sigma + betaI*mu*p*theta0^2 + betaI*mu^2*p*theta0 + 2*betaC*eta*mu*p*sigma + 2*betaI*eta*mu*p*theta0 + betaC*eta*p*sigma*theta0 + betaC*mu*p*sigma*theta0 + betaC*p*sigma^2*theta0*zeta + betaI*p*sigma*theta0^2*zeta + betaI*mu*p*sigma*theta0*zeta + betaI*eta*p*sigma*theta0*zeta))/((p - 1)^2*(eta + mu + sigma)^2*(eta + mu + theta0)^2))^(1/2) + p*sigma*theta0*((- betaI*eta^2 - betaI*mu^2 + eta*sigma^2 + eta^2*sigma + eta*theta0^2 + eta^2*theta0 + mu*sigma^2 + mu^2*sigma + mu*theta0^2 + mu^2*theta0 + sigma*theta0^2 + sigma^2*theta0 - betaC*p*sigma^2 - betaI*p*theta0^2 - 2*betaI*eta*mu - betaI*eta*sigma - betaI*eta*theta0 - betaI*mu*sigma - betaI*mu*theta0 + 2*eta*mu*sigma + 2*eta*mu*theta0 - betaI*sigma*theta0 + 2*eta*sigma*theta0 + 2*mu*sigma*theta0 + betaI*eta^2*p + betaI*mu^2*p + 2*betaI*eta*mu*p - betaC*p*sigma*theta0 + betaC*p*sigma^2*zeta + betaI*p*theta0^2*zeta + betaI*eta*p*sigma*zeta + betaI*eta*p*theta0*zeta + betaI*mu*p*sigma*zeta + betaI*mu*p*theta0*zeta + betaC*p*sigma*theta0*zeta + betaI*p*sigma*theta0*zeta)^2/((p - 1)^2*(eta + mu + sigma)^2*(eta + mu + theta0)^2) - (4*(2*eta*mu + eta*sigma + eta*theta0 + mu*sigma + mu*theta0 + sigma*theta0 + eta^2 + mu^2 - betaI*eta*p - betaI*mu*p - betaC*p*sigma - betaI*p*theta0 + betaI*eta*p*zeta + betaI*mu*p*zeta + betaC*p*sigma*zeta + betaI*p*theta0*zeta)*(sigma^2*theta0^2 - betaC*mu*sigma^2 - betaC*mu^2*sigma - betaI*mu*theta0^2 - betaI*mu^2*theta0 - betaC*sigma^2*theta0 - betaI*sigma*theta0^2 + eta*sigma*theta0^2 + eta*sigma^2*theta0 + eta^2*sigma*theta0 + mu*sigma*theta0^2 + mu*sigma^2*theta0 + mu^2*sigma*theta0 - betaC*eta*sigma^2 - betaC*eta^2*sigma - betaI*eta*theta0^2 - betaI*eta^2*theta0 - 2*betaC*eta*mu*sigma - 2*betaI*eta*mu*theta0 - betaC*eta*sigma*theta0 - betaI*eta*sigma*theta0 - betaC*mu*sigma*theta0 - betaI*mu*sigma*theta0 + 2*eta*mu*sigma*theta0 + betaC*eta*p*sigma^2 + betaC*eta^2*p*sigma + betaI*eta*p*theta0^2 + betaI*eta^2*p*theta0 + betaC*mu*p*sigma^2 + betaC*mu^2*p*sigma + betaI*mu*p*theta0^2 + betaI*mu^2*p*theta0 + 2*betaC*eta*mu*p*sigma + 2*betaI*eta*mu*p*theta0 + betaC*eta*p*sigma*theta0 + betaC*mu*p*sigma*theta0 + betaC*p*sigma^2*theta0*zeta + betaI*p*sigma*theta0^2*zeta + betaI*mu*p*sigma*theta0*zeta + betaI*eta*p*sigma*theta0*zeta))/((p - 1)^2*(eta + mu + sigma)^2*(eta + mu + theta0)^2))^(1/2) + betaC*p*sigma^2*zeta + betaI*p*theta0^2*zeta + betaI*eta*p*sigma*zeta + betaI*eta*p*theta0*zeta + betaI*mu*p*sigma*zeta + betaI*mu*p*theta0*zeta + betaC*p*sigma*theta0*zeta + betaI*p*sigma*theta0*zeta)/(2*(2*eta*mu + eta*sigma + eta*theta0 + mu*sigma + mu*theta0 + sigma*theta0 + eta^2 + mu^2 - betaI*eta*p - betaI*mu*p - betaC*p*sigma - betaI*p*theta0 + betaI*eta*p*zeta + betaI*mu*p*zeta + betaC*p*sigma*zeta + betaI*p*theta0*zeta));

end
alpha = max(alpha_temp,0);
end

